<a href="https://colab.research.google.com/github/Aasish357/Generative-AI-Portfolio/blob/main/liner_regression_with_gda_(no_libraries).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
age = [20, 30, 25, 40, 27, 28, 22, 24, 31]
exp = [0, 5, 2, 10, 4, 3.5, 1, 2, 6]

import numpy as np
age = np.array(age)
exp = np.array(exp)
income = age * 2 + exp * 3 + 5

In [27]:
# task : based on age, exp predict income.
# step1: feature matrix (input matrix).
ones = np.ones(len(age))
X = np.c_[ones, age, exp]
X.shape

(9, 3)

In [28]:
Y = np.c_[income]
Y.shape

(9, 1)

In [29]:
# step 3: random weights.
np.random.seed(101)
W = np.random.random((X.shape[1], Y.shape[1])) *2 -1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155]])

In [30]:
# trial 1.
# prediction
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta * 0.02
print(" Current Loss ", loss)

 Current Loss  5458.898860217916


In [31]:
# trial 2.
# prediction
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta * 0.02
print(" Current Loss ", loss)

 Current Loss  1229310.0198956437


In [32]:
# trial 3
# prediction
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta * 0.02
print(" Current Loss ", loss)

 Current Loss  278905762.2752112


In [33]:
# based on above trials ,  loss keep on increasing.
# solution : scaling featurs and labels.

In [34]:
def scale(x):
     return (x-x.mean())/x.std()

In [35]:
scale(age).std()

np.float64(1.0)

In [36]:

scale(exp).std()


np.float64(1.0000000000000002)

In [37]:
scale(income).std()

np.float64(1.0)

In [38]:
X_original = X.copy()
def scaleMatrix(x):
 for i in range(x.shape[1]):
   if i!=0:
        x[:, i] = scale(x[:, i])
 return x


In [39]:
X = scaleMatrix(X)
X

array([[ 1.        , -1.33414263, -1.30201447],
       [ 1.        ,  0.45798926,  0.44696019],
       [ 1.        , -0.43807668, -0.60242461],
       [ 1.        ,  2.25012115,  2.19593486],
       [ 1.        , -0.07965031,  0.09716526],
       [ 1.        ,  0.09956288, -0.07773221],
       [ 1.        , -0.97571625, -0.95221954],
       [ 1.        , -0.61728987, -0.60242461],
       [ 1.        ,  0.63720245,  0.79675513]])

In [40]:
Y_original = Y.copy()
Y = scale(Y)

In [41]:
# trials after scaling.
np.random.seed(101)
r = X.shape[1]
c = Y.shape[1]
W = np.random.random((r, c)) * 2 - 1
W

array([[ 0.03279726],
       [ 0.14133517],
       [-0.94305155]])

In [42]:
# trial 1.
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta * 0.02
print("Current loss ", loss)

Current loss  3.2453659375004267


In [43]:
# trial 2.
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta * 0.02
print("Current loss ", loss)

Current loss  2.9920377238515714


In [44]:
# trial 3
ycap = X.dot(W)
loss = ((Y-ycap)**2).mean()
delta = X.T.dot(Y-ycap)/Y.size
W += delta * 0.02
print("Current loss ", loss)

Current loss  2.7585038659152286


In [45]:
convergence = 0.0000001
ploss =0
flag=0
for i in range(100000):
     ycap = X.dot(W)
     closs = ((Y-ycap)**2).mean()
     if i%100==0:
       print(f"Current loss after {i+1} iterations {closs}")
     delta = X.T.dot(Y-ycap)/Y.size
     W += delta * 0.02
     if np.abs(ploss-closs)<=convergence:
          print(f" Training is completed after {i+1} iterations ")
          flag=1
          break
     ploss = closs

if flag==0:
  print(" Training not completed , run few more iterations ")


Current loss after 1 iterations 2.543217620112224
Current loss after 101 iterations 0.0037074985808627763
Current loss after 201 iterations 0.002870616908817354
Current loss after 301 iterations 0.0027945631551455938
Current loss after 401 iterations 0.0027209997276762877
Current loss after 501 iterations 0.0026493775658244143
Current loss after 601 iterations 0.002579640726066166
Current loss after 701 iterations 0.0025117394988555222
Current loss after 801 iterations 0.0024456255657733426
Current loss after 901 iterations 0.0023812518816902005
Current loss after 1001 iterations 0.0023185726398227695
Current loss after 1101 iterations 0.0022575432391129515
Current loss after 1201 iterations 0.0021981202524904227
Current loss after 1301 iterations 0.002140261395970897
Current loss after 1401 iterations 0.0020839254985679017
Current loss after 1501 iterations 0.0020290724729964383
Current loss after 1601 iterations 0.001975663287147847
Current loss after 1701 iterations 0.00192365993631

In [46]:
# rsquare.
rss = ((Y-ycap)**2).sum()
tss = ((Y-Y.mean())**2).sum()
rs = 1 - (rss/tss)
rs

np.float64(0.9996252351777959)